# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8072eb276937b32b1504ce7e83029e6fe6a9f74c9d721ebfd2ddadd3c6f750da51718e882a8e1b7312555e25ca051b577457202df41acd9da88d6d253f4cefd0

test:
  secret_key_base: edd953338e625041ecab058c55bf8799081e3fbf911ec1c1ec3d4b602254a445e24294f0db5eac9eaec240a00fb04c2d5b440c5108ed51db14b00fada5ef7929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
